version: '3.8'

networks:
  blog_app:

services:
  mysql:
    image: mysql:8
    container_name: blog-mysql
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    volumes:
      - ./docker/database/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - blog_app

  nginx:
    image: 'nginx:alpine'
    container_name: blog-nginx
    ports:
      - '8180:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - blog_app

  php:
    build: ./docker/php
    container_name: blog-php
    volumes:
      - .:/var/www/html
      - ./php/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
    ports:
      - '9000:9000'
    networks:
      - blog_app

volumes:
  db_data: {}
